### ISSUE TITLE
Background Geolocation

### ISSUE THREAD

**Issue by gusilveiramp** [shobshop/react-native-geofence#1]
Hey, first of all, congratulations for the project! It was very helpful!
Is possible to use it with Background monitoring?

Geofence's will alert user even ig the app is closed or in background?

**Comment by PaperMonster** [comment]
First of all, thanks for your interest in our work. Actually this plugin was created specifically for using in our projects so it might not be well-maintained and documented. If you found a bug, feel free to inform us but there'll be no ETA for fixes.

Answer to your question is, yes. We've just handled cases like app killed and device reboot in Android last week but haven't updated docs yet. I'll give you latest configurations you'll need for background geofence monitoring here for a time being.

**1. Set listeners outside components**
After app is killed (swiped out from recent apps or killed by OS) and user enter/exit geofences, app will be silently launched in background with no React Native component being rendered (not even App component) and fire `GeofenceEvent.Enter` or `GeofenceEvent.Exit` event. So it is important to register event listeners to these 2 events at the moment app starts **outside** the App component. For example, in app.js before the App component like this:
````
import React from 'react';
import RNGeofence, { GeofenceEvent } from 'react-native-geofence';

RNGeofence.on(GeofenceEvent.Enter, ({identifier}) => {
        console.log('Enter geofence: ' + identifier);
});
RNGeofence.on(GeofenceEvent.Exit, ({identifier}) => {
        console.log('Exit geofence: ' + identifier);
 });
class App extends React.Component {
...
````
**2. "Always" location authorization must be granted in iOS**
Otherwise geofence would stop monitoring when it enters background. Make sure app informs user to choose correct choice when being asked for permission.

**3. Listen to `GeofenceEvent.DeviceBootCompleted` in Android**
Monitored geofences are cleared on device reboot in Android, so app needs to listen to another event named `GeofenceEvent.DeviceBootCompleted` to initialize and re-add (persisted) geofences again in background. For example:
````
import React from 'react';
import RNGeofence, { GeofenceEvent } from 'react-native-geofence';

RNGeofence.on(GeofenceEvent.Enter, ({identifier}) => { ... });
RNGeofence.on(GeofenceEvent.Exit, ({identifier}) => { ... });
RNGeofence.on(GeofenceEvent.DeviceBootCompleted, () => {
     // Re-initialize
      RNGeofence.hasPlayServices({ autoResolve: true }).then(() => RNGeofence.initialize()).then(() => isPermissionSufficientForGeofence()).then(granted => {
        if(granted) {
            // Re-add geofences
            getSavedLocations().then(locations => {
              monitorGeofences(locations);
            });
        }
      });
    });
class App extends React.Component {
...
````
**4. Add permission and BroadcastReceiver to AndroidManifest**
Add following lines inside `<application>` element in the file (note the package name has changed from the docs)
````
<!-- RNGeofence -->
<service android:name="com.shobshop.react.geofence.GeofenceTransitionsIntentService" />
<receiver
    android:name="com.shobshop.react.geofence.DeviceBootCompleteReceiver"
    android:enabled="true"
    android:exported="false" >
    <intent-filter>
         <action android:name="android.intent.action.BOOT_COMPLETED" />
         <action android:name="android.location.MODE_CHANGED" />
         <action android:name="android.location.PROVIDERS_CHANGED" />
    </intent-filter>
</receiver>
````

Hope this helps.

**Comment by gusilveiramp** [comment]
Great! Thank you so much for all that.
I had a problem with path to MainApplication.java, so a change it from `import com.shobshop.RNGeofencePackage;` to `import com.shobshop.react.geofence.RNGeofencePackage;` and everything works, but the build process stop on RNGeofencePackage.java file.
This is the error generated:

```
Error:
C:\dev\rn\geoTreino\android\app\src\main\java\com\geotreino\MainApplication.java:27: error: constructor RNGeofencePackage in class RNGeofencePackage cannot be applied to given types;
          new RNGeofencePackage()
          ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
```

So, on line 22 of the RNGeofencePackage.java file, if I comment the function
```
//public RNGeofencePackage(Context context) {
//        mContext = context;
//}
```
after this, the build process reaches 100% and the application starts, but the app shows the red screen error with the following message:
![error-rn](https://user-images.githubusercontent.com/5175759/34369475-1c0b837e-eaa3-11e7-94db-415aadbd15a3.jpeg)

It seems that the error is related to googlePlayServices, at line 117 of the RNGeofenceModule.java file.

line 117:
`int status = googleApiAvailability.isGooglePlayServicesAvailable(mContext);`

Any help?

**Comment by PaperMonster** [comment]
My bad. I forgot the recently-added extra argument in RNGeofencePackage's constructor. Please make a change in MainApplication.java from `new RNGeofencePackage()` to `new RNGeofencePackage(getApplicationContext())`.

**Comment by gusilveiramp** [comment]
I have no words to thank you.
Everything is working perfectly now.
Thank you my friend.

**Comment by PaperMonster** [comment]
Cheers! Feel free to reopen this if you encounter any problem.
